### PR TITLE
[release-1.12] bump istio v1.19.6

### PR DESCRIPTION
**Pull request by dprotaso**

### CODE REVIEW

**Comment by ReToCode** [comment]
Hm there are conflicts on prow builds?

**Comment by dprotaso** [comment]
It's a weird prow bug - the branch was opened against main by accident so you see the main jobs - `latest_net-istio_main`

Changing the base target to release-1.11 made the release branch jobs show up `latest_net-istio_release-1.12` but it doesn't remove the main jobs

Since everything passed tide is just looking for an `lgtm` - ` Not mergeable. Needs lgtm label. `

**Review by gabo1208 — APPROVED** [review]

**Pull request merged**
