### PR TITLE
preserve appropriate header matches when creating the virtualservice

### PR DESCRIPTION
**Pull request by dprotaso**
## Changes

- 🐞  Properly propagate route header matching rules to the virtual service

/kind <kind>

Fixes: https://github.com/knative-extensions/net-istio/issues/847 https://github.com/knative-extensions/net-istio/issues/1313

**Release Note**

```release-note
Properly propagate route header matching rules to the virtual service
```

### CODE REVIEW

**Comment by dprotaso** [comment]
Going to verify in serving

**Comment by dprotaso** [comment]
Testing here: https://github.com/knative/serving/pull/15405

**Comment by dprotaso** [comment]
All serving checks are good - https://github.com/knative/serving/pull/15405

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
